### ISSUE TITLE
UnboundLocalError: local variable 'block_in' referenced before assignment

### ISSUE THREAD

**Issue by dranzerstar** [lllyasviel/Paints-UNDO#1]
After fetching all the files,
```
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
The config attributes {'latents_mean': None, 'latents_std': None, 'shift_factor': None, 'use_post_quant_conv': True, 'use_quant_conv': True} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
```

```
Traceback (most recent call last):
  File "D:\diffusionai\Paints-UNDO\gradio_app.py", line 47, in <module>
    video_pipe = LatentVideoDiffusionPipeline.from_pretrained(
  File "D:\diffusionai\Paints-UNDO\diffusers_vdm\pipeline.py", line 73, in from_pretrained
    vae=VideoAutoencoderKL.from_pretrained(os.path.join(local_folder, "vae")),
  File "D:\diffusionai\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\diffusionai\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hub_mixin.py", line 277, in from_pretrained
    instance = cls._from_pretrained(
  File "D:\diffusionai\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hub_mixin.py", line 485, in _from_pretrained
    model = cls(**model_kwargs)
  File "D:\diffusionai\Paints-UNDO\diffusers_vdm\vae.py", line 792, in __init__
    self.encoder = Encoder(double_z=double_z, z_channels=z_channels, resolution=resolution, in_channels=in_channels,
  File "D:\diffusionai\Paints-UNDO\diffusers_vdm\vae.py", line 200, in __init__
    self.mid.block_1 = ResnetBlock(in_channels=block_in,
UnboundLocalError: local variable 'block_in' referenced before assignment
```

**Comment by jtydhr88** [comment]
If you are on windows, you need to install Triton manual, but I don’t think it causes the next error

**Comment by barepixels** [comment]
Triton is not need.  I get Triton error but it is working
