### ISSUE TITLE
OSError: Can't load tokenizer for 'lllyasviel/paints_undo_single_frame'. 

### ISSUE THREAD

**Issue by QinHaisheng** [lllyasviel/Paints-UNDO#28]
(paints_undo) G:\Paints-UNDO>python gradio_app.py
Traceback (most recent call last):
  File "G:\Paints-UNDO\gradio_app.py", line 39, in <module>
    tokenizer = CLIPTokenizer.from_pretrained(model_name, subfolder="tokenizer")
  File "G:\miniconda3\envs\paints_undo\lib\site-packages\transformers\tokenization_utils_base.py", line 2094, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'lllyasviel/paints_undo_single_frame'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'lllyasviel/paints_undo_single_frame' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

how should i do...?

**Comment by jolene718** [comment]
Hi raxar81, I had the same problem as Qin did. I have taken your advice, but I got:
 (paints_undo) C:\Users\14583\Paints-UNDO>python gradio_app.py
Traceback (most recent call last):
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\14583\anaconda3\envs\paints_undo\lib\site-packages\urllib3\u
What should I do? I am a new learner, thank you.
