### ISSUE TITLE
Unable to running step 1 generate prompt

### ISSUE THREAD

**Issue by zzc0208** [lllyasviel/Paints-UNDO#46]
I am located in mainland China and cannot directly access huggingface. I used a mirror source to download the 19 required files. The download has been completed and read from the local, but I cannot execute step 1
```shell
(sd) linjl@bme-server:~/Paints-UNDO$ python gradio_app.py
/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
The config attributes {'shift_factor': None, 'use_post_quant_conv': True, 'use_quant_conv': True} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
Fetching 19 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 90972.35it/s]
Loading weights from local directory
Loading weights from local directory
Loading weights from local directory
Unload to CPU: AutoencoderKL
Unload to CPU: UNet3DModel
Unload to CPU: CLIPTextModel
Unload to CPU: ModifiedUNet
Unload to CPU: ImprovedCLIPVisionModelWithProjection
Unload to CPU: VideoAutoencoderKL
Unload to CPU: CLIPTextModel
Unload to CPU: Resampler
/home/linjl/Paints-UNDO/diffusers_helper/k_diffusion.py:43: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  alphas_cumprod = torch.tensor(np.cumprod(alphas, axis=0), dtype=torch.float32)
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.27.0, however version 4.29.0 is available, please upgrade.
--------
Traceback (most recent call last):
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/blocks.py", line 1788, in process_api
    result = await self.call_function(
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/blocks.py", line 1340, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/linjl/Paints-UNDO/gradio_app.py", line 115, in interrogator_process
    return wd14tagger.default_interrogator(x)
  File "/home/linjl/Paints-UNDO/wd14tagger.py", line 33, in default_interrogator
    model_onnx_filename = download_model(
  File "/home/linjl/Paints-UNDO/wd14tagger.py", line 23, in download_model
    download_url_to_file(url=url, dst=temp_path)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/torch/hub.py", line 622, in download_url_to_file
    u = urlopen(req)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
```

**Comment by victorca25** [comment]
Can you try something similar to: https://github.com/lllyasviel/Paints-UNDO/issues/44 ?

Seems to be related with wd14tagger

**Comment by KiedaTamashi** [comment]
i have the some problem. Have u solved it?

`urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>`

**Comment by lllrj** [comment]
> 我遇到了一些问题。你解决了吗？
> 
> `urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>`

I think the reasion is you are in China.
wd14tagger.py will help you download these file by huggingface. 
You can't download smoothly the onnx and csv.
My solution is that manually download these files by youself like #44.

**Comment by scooller** [comment]
I have a similar error but when loading the image

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\scool\AppData\Roaming\Python\Python310\site-packages\uvicorn\protocols\http\h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\scool\AppData\Roaming\Python\Python310\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\gradio\route_utils.py", line 713, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\gradio\route_utils.py", line 729, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\fastapi\dependencies\utils.py", line 813, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\fastapi\_compat.py", line 283, in get_model_fields
    return [
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\fastapi\_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\fastapi\_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "C:\Users\scool\.conda\envs\paints_undo\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type`

**Comment by T-K-233** [comment]
@scooller I solve this issue by upgrading gradio:

```bash
pip install gradio==4.43.0
```

**Comment by scooller** [comment]
Thanks it Working now but Now I have an error when generating video
