### ISSUE TITLE
It's not opening at http://0.0.0.0:7860 but getting this

### ISSUE THREAD

**Issue by oly1kenobi** [lllyasviel/Paints-UNDO#62]
C:\Users\droly\Paints-UNDO>python gradio_app.py
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\droly\miniconda3\envs\paints_undo\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\droly\miniconda3\envs\paints_undo\lib\site-packages\xformers\triton\softmax.py", line 14, in <module>
    from xformers.triton.k_softmax import _softmax, _softmax_backward
  File "C:\Users\droly\miniconda3\envs\paints_undo\lib\site-packages\xformers\triton\k_softmax.py", line 8, in <module>
    import triton.language as tl
ModuleNotFoundError: No module named 'triton.language'
The config attributes {'shift_factor': None, 'use_post_quant_conv': True, 'use_quant_conv': True} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
Fetching 19 files: 100%|███████████████████████████████████████████████████████████████████████| 19/19 [00:00<?, ?it/s]
Loading weights from local directory
Loading weights from local directory
Loading weights from local directory
Unload to CPU: ModifiedUNet
Unload to CPU: CLIPTextModel
Unload to CPU: CLIPTextModel
Unload to CPU: UNet3DModel
Unload to CPU: VideoAutoencoderKL
Unload to CPU: ImprovedCLIPVisionModelWithProjection
Unload to CPU: Resampler
Unload to CPU: AutoencoderKL
C:\Users\droly\Paints-UNDO\diffusers_helper\k_diffusion.py:43: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  alphas_cumprod = torch.tensor(np.cumprod(alphas, axis=0), dtype=torch.float32)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by barepixels** [comment]
For me, I edit near last line of gradio_app.py

to `block.queue().launch(server_name='127.0.0.1')`

**Comment by packetlost** [comment]
> For me, I edit near last line of gradio_app.py
> 
> to `block.queue().launch(server_name='127.0.0.1')`

For the win!

**Comment by oly1kenobi** [comment]
> For me, I edit near last line of gradio_app.py
> 
> to `block.queue().launch(server_name='127.0.0.1')`

Thanks, but where would I edit that? NEWB here
Thanks

**Comment by packetlost** [comment]
> gradio_app.py

That file is in your program directory. Edit gradio_app.py with Notepad and scroll to the bottom. Highlight the entire last line and paste the corrected line.

**Comment by Its-Endless** [comment]
You can just change the http in the browser from  http://0.0.0.0:7860  to  http://127.0.0.1:7860

**Comment by choiwangchun** [comment]
I'm running it with co-lab, and even if I replace the last line with block.queue().launch(server_name='127.0.0.1'), I can't connect.

**Comment by DimitriMichel** [comment]
Just prefix it with localhost `localhost:7860` which essenstially translates to what @Its-Endless says with [http://127.0.0.1:7860/](http://127.0.0.1:7860/)
