### ISSUE TITLE
Unable to generate keyframe

### ISSUE THREAD

**Issue by aldrichzhang0612** [lllyasviel/Paints-UNDO#88]
"Hi everyone, when I deploy the model I can generate image cues fine, but when I try to generate video keyframes I keep getting an error."
**_The error message is as follows:
Load to GPU: CLIPTextModel
Unload to CPU: CLIPTextModel
Load to GPU: ModifiedUNet
Traceback (most recent call last):
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\gradio\routes.py", line 738, in predict
    output = await route_utils.call_process_api(
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\gradio\blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\gradio\blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\gradio\utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\AI\aldrich\Paints-UNDO\gradio_app.py", line 136, in process
    latents = k_sampler(
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\AI\aldrich\Paints-UNDO\diffusers_helper\k_diffusion.py", line 143, in __call__
    results = sample_dpmpp_2m(self.k_model, latents, sigmas, extra_args=sampler_kwargs, progress_tqdm=progress_tqdm)
  File "H:\AI\aldrich\Paints-UNDO\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\AI\aldrich\Paints-UNDO\diffusers_helper\k_diffusion.py", line 19, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
_**IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got Progress)**_**

Below is my hardware environment:
CPU:Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
GPU:NVIDIA GeForce GTX 1650
System Specifications：Windows 10

I'd really appreciate your help with this, thanks a lot!

**Comment by FurkanGozukara** [comment]
i published installers : https://github.com/lllyasviel/Paints-UNDO/issues/100
