### ISSUE TITLE
python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by ausalt** [lllyasviel/Paints-UNDO#90]
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
 import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

**Comment by ReloadProcz** [comment]
Well I think you didn't build up the conda environment correctly. Did you really install conda and set the conda\bin to the %PATH% and strictly follow the README?

**Comment by nezdot** [comment]
> python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [6 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in import torch ModuleNotFoundError: No module named 'torch' [end of output]

I'm having the same issue, did you manage to fix it?

> Well I think you didn't build up the conda environment correctly. Did you really install conda and set the conda\bin to the %PATH% and strictly follow the README?

I do have the conda directories added to path but unfortunately it still doesn't work.
I also tried installing either miniconda or anaconda to see if that changes anything but no luck.

**Comment by FurkanGozukara** [comment]
i published installers : https://github.com/lllyasviel/Paints-UNDO/issues/100
