### ISSUE TITLE
problem generating video.

### ISSUE THREAD

**Issue by DiosMuerto** [lllyasviel/Paints-UNDO#96]
I can add images normally and generate the prompt, I can also generate the frame keys

but when generating the video I get an error.
any solution
I have a 3090

To create a public link, set `share=True` in `launch()`.
Load to GPU: AutoencoderKL
Unload to CPU: AutoencoderKL
Load to GPU: CLIPTextModel
Unload to CPU: CLIPTextModel
Load to GPU: ModifiedUNet
Unload to CPU: ModifiedUNet
Load to GPU: AutoencoderKL
Unload to CPU: AutoencoderKL
Load to GPU: CLIPTextModel
Unload to CPU: CLIPTextModel
Load to GPU: ImprovedCLIPVisionModelWithProjection
Load to GPU: Resampler
Unload to CPU: ImprovedCLIPVisionModelWithProjection
Unload to CPU: Resampler
Load to GPU: VideoAutoencoderKL
Traceback (most recent call last):
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context    return func(*args, **kwargs)
  File "C:\paints\Paints-UNDO\gradio_app.py", line 222, in process_video
    frames, im1, im2 = process_video_inner(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context    return func(*args, **kwargs)
  File "C:\paints\Paints-UNDO\gradio_app.py", line 190, in process_video_inner
    input_frame_latents, vae_hidden_states = video_pipe.encode_latents(input_frames, return_hidden_states=True)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context    return func(*args, **kwargs)
  File "C:\paints\Paints-UNDO\diffusers_vdm\pipeline.py", line 102, in encode_latents
    encoder_posterior, hidden_states = self.vae.encode(x, return_hidden_states=return_hidden_states)
  File "C:\paints\Paints-UNDO\diffusers_vdm\vae.py", line 804, in encode
    h, hidden = self.encoder(x, return_hidden_states)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\paints\Paints-UNDO\diffusers_vdm\vae.py", line 249, in forward
    h = self.mid.attn_1(h)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\paints\Paints-UNDO\diffusers_vdm\vae.py", line 411, in forward
    h_ = self.attention(h_)
  File "C:\paints\Paints-UNDO\diffusers_vdm\vae.py", line 397, in attention
    out = chunked_attention(
  File "C:\paints\Paints-UNDO\diffusers_vdm\vae.py", line 36, in chunked_attention
    out = xformers.ops.memory_efficient_attention(q, k, v)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\xformers\ops\fmha\__init__.py", line 301, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\xformers\ops\fmha\__init__.py", line 462, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\xformers\ops\fmha\__init__.py", line 481, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\xformers\ops\fmha\dispatch.py", line 135, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\SR\.conda\envs\paints_undo\lib\site-packages\xformers\ops\fmha\dispatch.py", line 76, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(2, 2688, 1, 512) (torch.float16)
     key         : shape=(2, 2688, 1, 512) (torch.float16)
     value       : shape=(2, 2688, 1, 512) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`fa2F@0.0.0` is not supported because:
    max(query.shape[-1], value.shape[-1]) > 256
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`cutlassF-pt` is not supported because:
    xFormers wasn't build with CUDA support

**Comment by BaiZe1998** [comment]
i meet the problem too!

**Comment by FurkanGozukara** [comment]
i published installers : https://github.com/lllyasviel/Paints-UNDO/issues/100
